<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Minor_Miseries</RootNamespace>
		<LangVersion>Latest</LangVersion>
		<IsPackable>false</IsPackable>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyName>Minor_Miseries</AssemblyName>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<TheLongDarkPath>D:\SteamLibrary\steamapps\common\TheLongDark</TheLongDarkPath>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Resources\Icons\Afflictions\Alt\BackPain_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\BadDream_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\BareSkin_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\Blister_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\NightTerror_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\OverconfidenceRisk_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\Overconfidence_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\Scratch_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\SensitiveHand_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\ShoulderTrauma_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\SmallCut_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\SoreNeck_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\Splinter_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\StuckFood_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Alt\WristTrauma_ALT.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\BackPain.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\BadDream.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\BareSkin.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\Blister.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\NightTerror.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\Overconfidence.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\OverconfidenceRisk.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\Scratch.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\SensitiveHand.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\ShoulderTrauma.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\SmallCut.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\SoreNeck.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\Splinter.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\StuckFood.png" />
		<None Remove="Resources\Icons\Afflictions\Classic\WristTrauma.png" />
		<None Remove="Resources\Icons\Buffs\Alt\PeaceOfMind_ALT.png" />
		<None Remove="Resources\Icons\Buffs\Alt\ProtectedArms_ALT.png" />
		<None Remove="Resources\Icons\Buffs\Alt\ProtectedHands_ALT.png" />
		<None Remove="Resources\Icons\Buffs\Classic\PeaceOfMind.png" />
		<None Remove="Resources\Icons\Buffs\Classic\ProtectedArms.png" />
		<None Remove="Resources\Icons\Buffs\Classic\ProtectedHands.png" />
		<None Remove="Resources\Localization\Localization.json" />
	</ItemGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="AfflictionLogic.cs" />
		<Compile Include="AfflictionSaveHelper.cs" />
		<Compile Include="Afflictions\BackPain.cs" />
		<Compile Include="Afflictions\BadDream.cs" />
		<Compile Include="Afflictions\BareSkin.cs" />
		<Compile Include="Afflictions\Blister.cs" />
		<Compile Include="Afflictions\Buffs\PeaceOfMind.cs" />
		<Compile Include="Afflictions\Buffs\ProtectedArms.cs" />
		<Compile Include="Afflictions\Buffs\ProtectedHands.cs" />
		<Compile Include="Afflictions\DebugAffliction.cs" />
		<Compile Include="Afflictions\NightTerror.cs" />
		<Compile Include="Afflictions\Overconfidence.cs" />
		<Compile Include="Afflictions\SensitiveHand.cs" />
		<Compile Include="Afflictions\ShoulderTrauma.cs" />
		<Compile Include="Afflictions\SmallCut.cs" />
		<Compile Include="Afflictions\SoreNeck.cs" />
		<Compile Include="Afflictions\WristTrauma.cs" />
		<Compile Include="BuffLogic.cs" />
		<Compile Include="Core.cs" />
		<Compile Include="DevConsoleCommands.cs" />
		<Compile Include="Patches\AfflictionEffects.cs" />
		<Compile Include="Patches\BreakdownPatch.cs" />
		<Compile Include="Patches\CraftingPatch.cs" />
		<Compile Include="MMSettings.cs" />
		<Compile Include="Afflictions\OverconfidenceRisk.cs" />
		<Compile Include="Afflictions\Scratch.cs" />
		<Compile Include="Afflictions\Splinter.cs" />
		<Compile Include="Afflictions\StuckFood.cs" />
		<Compile Include="Patches\FirearmsPatch.cs" />
		<Compile Include="Patches\RepairOnCrashPatch.cs" />
		<Compile Include="Persistence\MMState.cs" />
		<Compile Include="Persistence\SaveDataManager.cs" />
		<Compile Include="Resources\Localization\ILocalizableAffliction.cs" />
		<Compile Include="Resources\Localization\LocalizationRefresh.cs" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\BackPain_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\BadDream_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\BareSkin_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\Blister_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\NightTerror_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\OverconfidenceRisk_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\Overconfidence_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\Scratch_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\SensitiveHand_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\ShoulderTrauma_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\SmallCut_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\SoreNeck_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\Splinter_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\StuckFood_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Alt\WristTrauma_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\BackPain.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\BadDream.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\BareSkin.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\Blister.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\NightTerror.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\Overconfidence.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\OverconfidenceRisk.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\Scratch.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\SensitiveHand.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\ShoulderTrauma.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\SmallCut.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\SoreNeck.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\Splinter.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\StuckFood.png" />
		<EmbeddedResource Include="Resources\Icons\Afflictions\Classic\WristTrauma.png" />
		<EmbeddedResource Include="Resources\Icons\Buffs\Alt\PeaceOfMind_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Buffs\Alt\ProtectedArms_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Buffs\Alt\ProtectedHands_ALT.png" />
		<EmbeddedResource Include="Resources\Icons\Buffs\Classic\PeaceOfMind.png" />
		<EmbeddedResource Include="Resources\Icons\Buffs\Classic\ProtectedArms.png" />
		<EmbeddedResource Include="Resources\Icons\Buffs\Classic\ProtectedHands.png" />
		<EmbeddedResource Include="Resources\Localization\Localization.json" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="AfflictionComponent">
			<HintPath>$(TheLongDarkPath)\Mods\AfflictionComponent.dll</HintPath>
		</Reference>
		<Reference Include="ModSettings">
			<HintPath>$(TheLongDarkPath)\Mods\ModSettings.dll</HintPath>
		</Reference>
		<Reference Include="ModComponent">
			<HintPath>$(TheLongDarkPath)\Mods\ModComponent.dll</HintPath>
		</Reference>
		<Reference Include="ModData">
			<HintPath>$(TheLongDarkPath)\Mods\ModData.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="STBlade.Modding.TLD.Il2CppAssemblies.Windows" Version="2.51.0" />
		<PackageReference Include="STBlade.Modding.TLD.ModSettings" Version="1.9.0" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="System.Reflection" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="Il2Cpp" />
		<Using Include="HarmonyLib" />
		<Using Include="MelonLoader" />
		<Using Include="UnityEngine" />
		<Using Include="ModSettings" />
		<Using Include="ModComponent" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(TheLongDarkPath)/Mods" />
	</Target>
</Project>